### ISSUE TITLE
Put cvloop to conda-forge?

### ISSUE THREAD

**Issue by AndreaSuckro** [shoeffner/cvloop#15]
Not sure whether this is in plan, but having the cvloop not just on pip would be awesome! [Short docu](https://conda-forge.github.io/#add_recipe) and their responsible repo [Conda-Forge](https://github.com/conda-forge/staged-recipes)

**Comment by shoeffner** [comment]
I checked this out and it turns out that I need to have some tests (See conda-forge/staged-recipes#2995). I will take a look at that when I have some more time, as it is hard to test many of the functions around matplotlib and OpenCV. But I am sure I will find some things I can test properly which are not only API tests.
